language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1
    fast_finish: true

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit -v
